CREATE DATABASE BIBLIOTECA_VIRTUAL
GO

USE BIBLIOTECA_VIRTUAL
GO

/*CREACION DE LA TB TIPO PERSONA*/
CREATE TABLE TIPO_PERSONA(
ID_TIPO_PERSONA INT IDENTITY(1,1) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL UNIQUE
)
GO

/*CONSTRAINTS*/
ALTER TABLE TIPO_PERSONA
ADD CONSTRAINT PK_ID_TIPO_PERSONA
PRIMARY KEY(ID_TIPO_PERSONA)
GO

SELECT * FROM TIPO_PERSONA
GO

/*CREACION DE LA TABLA PERSONA*/
CREATE TABLE PERSONA(
ID_PERSONA INT IDENTITY(1,1) NOT NULL,
ID_TIPO_PERSONA INT NOT NULL,
ID_DISTRITO INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
DNI CHAR(8) NOT NULL UNIQUE,
TELEFONO CHAR(9) NOT NULL UNIQUE,
CORREO_ELEC VARCHAR(30) NOT NULL UNIQUE
)
GO

/*CONSTRAINTS*/
ALTER TABLE PERSONA
ADD CONSTRAINT PK_ID_PERSONA
PRIMARY KEY(ID_PERSONA)
GO

ALTER TABLE PERSONA
ADD CONSTRAINT FK_ID_TIPO_PERSONA
FOREIGN KEY(ID_TIPO_PERSONA) REFERENCES TIPO_PERSONA
GO

ALTER TABLE PERSONA
ADD CONSTRAINT FK_ID_DISTRITO
FOREIGN KEY(ID_DISTRITO) REFERENCES DISTRITOS(ID_DISTRITO)
GO


/*CREACION DE LA TABLA USUARIO*/

CREATE TABLE USUARIO(
ID_USUARIO INT NOT NULL,
USERNAME VARCHAR(30) NOT NULL UNIQUE,
CONTRASENA VARCHAR(40) NOT NULL,
ESTADO BIT NOT NULL
)
GO

/*CONSTRAINTS*/
ALTER TABLE USUARIO
ADD CONSTRAINT PK_ID_USUARIO
PRIMARY KEY(ID_USUARIO)
GO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_ID_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES PERSONA(ID_PERSONA)
GO


/*CREACION DE LA TABLA DISTRITOS*/
CREATE TABLE DISTRITOS(
ID_DISTRITO INT IDENTITY(1,1) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL
)
GO

/*CONSTRAINTS*/
ALTER TABLE DISTRITOS
ADD CONSTRAINT PK_ID_DISTRITO PRIMARY KEY(ID_DISTRITO)
GO


/*CREACION DE LA TABLA CATEGORIA*/
CREATE TABLE CATEGORIA(
ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL
)
GO

/*CONSTRAINTS*/
ALTER TABLE CATEGORIA
ADD CONSTRAINT PK_ID_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
GO

ALTER TABLE CATEGORIA
ADD CONSTRAINT UQ_DESCRIPCION UNIQUE(DESCRIPCION)
GO


/*CREACION DE LA TABLA AUTOR*/
CREATE TABLE AUTOR(
ID_AUTOR INT IDENTITY(1,1) NOT NULL,
NOMBRE_APELLIDO VARCHAR(30) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
NACIONALIDAD VARCHAR(20) NOT NULL,
ESTADO BIT NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE AUTOR
ADD CONSTRAINT PK_ID_AUTOR PRIMARY KEY(ID_AUTOR)
GO

ALTER TABLE AUTOR
ADD CONSTRAINT UQ_NOMBRE_APELLIDO UNIQUE(NOMBRE_APELLIDO)
GO


/*CREACION DE LA TABLA LIBROS*/
CREATE TABLE LIBROS(
ID_LIBRO INT IDENTITY(1,1) NOT NULL,
ID_AUTOR INT NOT NULL,
ID_EDITORIAL INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
TITULO VARCHAR(100) NOT NULL,
STOCK INT NOT NULL,
FECHA_PUBLICACION DATE NOT NULL,
RUTA_IMG_LIBRO VARCHAR(200) NOT NULL,
ESTADO BIT NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE LIBROS
ADD CONSTRAINT PK_ID_LIBRO PRIMARY KEY(ID_LIBRO)
GO

ALTER TABLE LIBROS
ADD CONSTRAINT FK_ID_AUTOR FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
GO

ALTER TABLE LIBROS
ADD CONSTRAINT FK_ID_EDITORIAL FOREIGN KEY(ID_EDITORIAL) REFERENCES EDITORIAL(ID_EDITORIAL)
GO

ALTER TABLE LIBROS
ADD CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
GO

ALTER TABLE LIBROS
ADD CONSTRAINT UQ_RUTA_IMG_LIBRO UNIQUE(RUTA_IMG_LIBRO)
GO

ALTER TABLE LIBROS
ADD CONSTRAINT UQ_TITULO_LIBRO UNIQUE(TITULO)
GO

/*CREACION DE LA TABLA DETALLE LIBROS*/
CREATE TABLE DETALLE_LIBRO(
ID_LIBRO INT NOT NULL,
SINOPSIS VARCHAR(400) NOT NULL

)
GO

/*CONSTRAINT*/
ALTER TABLE DETALLE_LIBRO
ADD CONSTRAINT PK_ID_LIBRO_SINOPSIS PRIMARY KEY(ID_LIBRO)
GO


ALTER TABLE DETALLE_LIBRO
ADD CONSTRAINT FK_ID_LIBRO_SINOPSIS FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO)
GO

ALTER TABLE DETALLE_LIBRO
ADD CONSTRAINT UQ_SINOPSIS UNIQUE(SINOPSIS)
GO


/*CREACION DE LA TABLA EDITORIAL*/
CREATE TABLE EDITORIAL(
ID_EDITORIAL INT IDENTITY(1,1) NOT NULL,
RAZON_SOCIAL VARCHAR(30) NOT NULL,
RUC CHAR(11) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
CORREO_ELEC VARCHAR(50) NOT NULL,
ESTADO BIT NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE EDITORIAL
ADD CONSTRAINT PK_ID_EDITORIAL PRIMARY KEY(ID_EDITORIAL)
GO

ALTER TABLE EDITORIAL
ADD CONSTRAINT UQ_RAZON_SOCIAL UNIQUE(RAZON_SOCIAL)
GO

ALTER TABLE EDITORIAL
ADD CONSTRAINT UQ_RUC UNIQUE(RUC)
GO

ALTER TABLE EDITORIAL
ADD CONSTRAINT UQ_DIRECCION UNIQUE(DIRECCION)
GO

ALTER TABLE EDITORIAL
ADD CONSTRAINT UQ_CORREO_ELEC UNIQUE(CORREO_ELEC)
GO


/*CREACION DE LA TABLA DETALLE LIBRO EDITORIAL*/
CREATE TABLE DETALLE_LIBROS_EDITORIAL(
ID_LIBRO INT NOT NULL,
ID_EDITORIAL INT NOT NULL,
STOCK INT NOT NULL,
FECHA_IMPRESION DATE NOT NULL,
ESTADO BIT NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE DETALLE_LIBROS_EDITORIAL
ADD CONSTRAINT PK_ID_LIBRO_EDITORIAL PRIMARY KEY(ID_LIBRO,ID_EDITORIAL)
GO

ALTER TABLE DETALLE_LIBROS_EDITORIAL
ADD CONSTRAINT FK_ID_LIBRO_DETALLE FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO)
GO

ALTER TABLE DETALLE_LIBROS_EDITORIAL
ADD CONSTRAINT FK_ID_EDITORIAL_DETALLE FOREIGN KEY(ID_EDITORIAL) REFERENCES EDITORIAL(ID_EDITORIAL)
GO


/*CREACION DE LA TABLA REGISTRO LIBROS*/
CREATE TABLE REGISTRO_LIBROS_EDITORIAL(
ID_PERSONA INT NOT NULL,
ID_LIBRO INT NOT NULL,
CANTIDAD_LIBROS INT NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE REGISTRO_LIBROS_EDITORIAL
ADD CONSTRAINT PK_ID_REGISTRO PRIMARY KEY(ID_PERSONA,ID_LIBRO)
GO

ALTER TABLE REGISTRO_LIBROS_EDITORIAL
ADD CONSTRAINT FK_ID_PERSONA_REGIS FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
GO

ALTER TABLE REGISTRO_LIBROS_EDITORIAL
ADD CONSTRAINT FK_ID_LIBROS_EDITORIAL_REGIS FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO)
GO


/*CREACION DE LA TABLA RESERVA VIRTUAL*/
CREATE TABLE RESERVA_VIRTUAL(
ID_RESERVA INT IDENTITY(1,1) NOT NULL,
ID_PERSONA INT NOT NULL,
FECHA_INICIO DATETIME NOT NULL,
FECHA_FINAL DATETIME NOT NULL,
ESTADO BIT NOT NULL

)
GO

/*CONSTRAINTS*/
ALTER TABLE RESERVA_VIRTUAL
ADD CONSTRAINT PK_RESERVA_VIRTUAL PRIMARY KEY(ID_RESERVA)
GO

ALTER TABLE RESERVA_VIRTUAL
ADD CONSTRAINT FK_ID_PERSONA_RESERVA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
GO


/*CREACION DE LA TABLA DETALLE RESERVA*/
CREATE TABLE DETALLE_RESERVA(
ID_RESERVA INT NOT NULL,
ID_LIBRO INT NOT NULL,
CANTIDAD INT NOT NULL,
ESTADO BIT NOT NULL
)
GO

/*CONSTRAINTS*/
ALTER TABLE DETALLE_RESERVA
ADD CONSTRAINT PK_ID_DETALLE_RESERVA PRIMARY KEY(ID_RESERVA, ID_LIBRO)
GO

ALTER TABLE DETALLE_RESERVA
ADD CONSTRAINT FK_ID_RESERVA_DETALLE FOREIGN KEY(ID_RESERVA) REFERENCES RESERVA_VIRTUAL(ID_RESERVA)
GO

ALTER TABLE DETALLE_RESERVA
ADD CONSTRAINT FK_ID_LIBRO_DETALLE FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO)
GO

ALTER TABLE DETALLE_RESERVA
ADD CONSTRAINT CK_CANTIDAD CHECK(CANTIDAD = 1)
GO
