/*CREACION DE LA VISTA CONSOLIDADO LIBROS*/
CREATE VIEW CONSOLIDADO_LIBRO AS
SELECT  L.ID_LIBRO,
		L.TITULO,
		C.DESCRIPCION AS CATEGORIA,
		A.NOMBRE_APELLIDO AS AUTOR,
		E.RAZON_SOCIAL AS EDITORIAL,
		L.STOCK,
		R.CANTIDAD_LIBROS AS CANTIDAD,
		L.FECHA_PUBLICACION,
		R.FECHA_REGISTRO,
		L.RUTA_IMG_LIBRO AS RUTA_IMAGEN,
		D.SINOPSIS,
		L.ESTADO
FROM LIBROS L
INNER JOIN AUTOR A ON L.ID_AUTOR=A.ID_AUTOR
INNER JOIN CATEGORIA C ON L.ID_CATEGORIA=C.ID_CATEGORIA
INNER JOIN EDITORIAL E ON L.ID_EDITORIAL=E.ID_EDITORIAL
INNER JOIN DETALLE_LIBRO D ON L.ID_LIBRO =D.ID_LIBRO
INNER JOIN REGISTRO_LIBROS_EDITORIAL R ON L.ID_LIBRO=R.ID_LIBRO
GO



/*CREACION DE LA VISTA CONSOLIDADO RESERVA*/
CREATE VIEW CONSOLIDADO_RESERVA AS
SELECT R.ID_RESERVA,
	   R.ID_PERSONA,
	   D.ID_LIBRO,
	   L.TITULO,
	   A.NOMBRE_APELLIDO AS AUTOR,
	   C.DESCRIPCION AS CATEGORIA,
	   E.RAZON_SOCIAL AS EDITORIAL,
	   R.FECHA_INICIO,
	   R.FECHA_FINAL,
	   D.ESTADO
FROM DETALLE_RESERVA D
INNER JOIN RESERVA_VIRTUAL R ON R.ID_RESERVA = D.ID_RESERVA
INNER JOIN LIBROS L ON D.ID_LIBRO = L.ID_LIBRO
INNER JOIN AUTOR A ON L.ID_AUTOR = A.ID_AUTOR
INNER JOIN CATEGORIA C ON L.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN EDITORIAL E ON L.ID_EDITORIAL = E.ID_EDITORIAL
GO
